### ISSUE TITLE
Build error on OSX with Xcode 6.x - fixed by Xcode 7.3

### ISSUE THREAD

**Issue by dpo** [ukoethe/vigra#250] opened 2015-07-03 10:13 UTC
Over at [Homebrew/Science](https://github.com/Homebrew/homebrew-science) we're having an [issue building Vigra](https://github.com/Homebrew/homebrew-science/issues/2428) on OSX. A web search suggests it might be due to a bug in the version of clang shipped with Xcode 6.x. The error occurs during `make check` and looks as follows:
```
[ 38%] Building CXX object test/multiconvolution/CMakeFiles/test_multiconvolution_speed.dir/speedtest.cxx.o
cd /tmp/vigra20150621-62775-cexkzn/vigra-1.10.0/build/test/multiconvolution && /usr/local/Library/ENV/4.3/clang++    -I/tmp/vigra20150621-62775-cexkzn/vigra-1.10.0/include -I/tmp/vigra20150621-62775-cexkzn/vigra-1.10.0/test/include    -o CMakeFiles/test_multiconvolution_speed.dir/speedtest.cxx.o -c /tmp/vigra20150621-62775-cexkzn/vigra-1.10.0/test/multiconvolution/speedtest.cxx
In file included from /tmp/vigra20150621-62775-cexkzn/vigra-1.10.0/test/math/test.cxx:41:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/typeinfo:61:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/exception:81:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:1195:21: error: call to '__test' is ambiguous
   typedef decltype(__test(declval<_Tp>())) type;
                    ^~~~~~
```
[Here](https://gist.github.com/anonymous/11f85ad1a2db789301de) is the complete build log and [here](https://gist.github.com/anonymous/11f85ad1a2db789301de#file-03-make-L92) is where the error occurs.

Thanks in advance!

**Comment by hmeine** [comment] 2015-09-03 08:54
I think I can reproduce this (using MacPorts) with XCode 6.4, Apple LLVM version 6.1.0 (clang-602.0.53), for me ``make check`` fails in ``test_math``.  The error reads:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:1195:21: error: call to '__test' is ambiguous
   typedef decltype(__test(declval<_Tp>())) type;
                    ^~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:1208:18: note: in instantiation of template class
      'std::__1::__numeric_type<vigra::FixedPoint16<1, 0> >' requested here
          bool = __numeric_type<_A1>::value &&
                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:734:14: note: in instantiation of default argument for
      '__promote<vigra::FixedPoint16<1, 0>, vigra::FixedPoint16<1, 0>, void>' required here
    typename __promote<_A1, _A2>::type
             ^~~~~~~~~~~~~~~~~~~
/Users/hmeine/vigra/test/math/test.cxx:1657:21: note: while substituting deduced template arguments into function template 'atan2' [with _A1 = vigra::FixedPoint16<1, 0>,
      _A2 = vigra::FixedPoint16<1, 0>]
        shouldEqual(vigra::atan2(FP1(0), FP1(1)), FP2(0));
                    ^
/Users/hmeine/vigra/include/vigra/unittest.hxx:128:31: note: expanded from macro 'shouldEqual'
    vigra::detail::equal_impl(left, right, #left " == " #right, __FILE__, __LINE__)
```

and then candidates for all builtin types are listed, such as `static double __test(long long);`, but I think the error is already somewhere in the above stack.  Ulli, can you look at the error messages?  How should these promote traits from the STL work with FixedPoint types?

**Comment by nieder** [comment] 2015-10-03 02:38
@ukoethe reported to me back in November that this is caused by a clang bug: https://llvm.org/bugs/show_bug.cgi?id=21083

**Comment by jakirkham** [comment] 2016-02-23 16:08
Yes, this is a clang bug. It is fixed in XCode 7.3. I encountered it as well when setting up CI. I know all versions of XCode 6.x had the problem. Though do not recall if an earlier version of 7 had the solution or not. I believe not.

**Comment by jakirkham** [comment] 2016-02-24 06:33
It should be possible to add workarounds in VIGRA to avoid this clang bug. I would need to try before I can say for sure whether this is doable.

**Comment by hmeine** [comment] 2016-03-03 09:18
I think this issue can be closed. It still serves as a reference, and if anybody is willing to make vigra work with the older clang, he/she is of course welcome and should reference this issue.

**Closed by hmeine** 2016-03-03 09:18 UTC
