### ISSUE TITLE
RandomForest.writeHDF5() seems to corrupt h5py module

### ISSUE THREAD

**Issue by stuarteberg** [ukoethe/vigra#374] opened 2016-06-10 20:42 UTC
The following test program consistently induces a "Bus Error" on my machine.  Strangely, the error does not occur within a vigra function, but only afterwards, when using h5py.

Using `git bisect`, I was able to identify the commit that introduced this problem: b847941d06223c9592a87505aaaa6b86239a5f43

```python
import tempfile
import numpy as np
import vigra
import h5py

tmp_dir = tempfile.mkdtemp()

# Create RF
features = np.random.random( (10, 5) ).astype( np.float32 )
labels = np.random.randint(1,3, size=(10, 1)).astype(np.uint32)    
rf = vigra.learning.RandomForest()
rf.learnRF(features, labels)

print "Writing RF..."
# If you comment out this line, the program does not crash
rf.writeHDF5(tmp_dir + '/written_by_vigra.h5', 'forest')

print "Creating new file..."
try:
    with h5py.File(tmp_dir + '/empty-file.h5', 'w') as f:
        print "Reading non-existent key. Should raise, not crash!"
        x = f['not-there']  # <---- Bus Error ??
except KeyError:
    pass

print "Never gets here..."
```

(The easiest (only?) way to reproduce the error is to attempt to access a non-existing value in an h5 file.  Normally, that is supposed to merely raise a `KeyError`, but instead the program crashes with a bus error.)

Of course, it is possible that somehow there is a bug in either `hdf5` or `h5py` that is merely exposed by this change in vigra...

This issue was previously reported in ilastik/lazyflow#211 and ilastik/ilastik#1210 by @svenpeter42.

**Comment by stuarteberg** [comment] 2016-06-10 21:33
I don't understand what, if anything, is wrong with b847941.  But indeed, reverting it seems to fix the crash. Hence, I've submitted #375.  Since the commit in question was just a performance improvement anyway (and probably not a major one), it's probably not worth investigating too much further.

**Comment by stuarteberg** [comment] 2016-06-10 21:35
Side note: This will finally allow me to update the ilastik conda recipes to use vigra 1.11, which will, in turn, allow me to merge the multicut workflow into ilastik's master branch.

**Comment by ukoethe** [comment] 2016-06-10 21:42
I can reproduce the crash using your test program, but the function `openCreateGroup_()` (which commit https://github.com/ukoethe/vigra/commit/b847941d06223c9592a87505aaaa6b86239a5f43 modifies) is not called at all. Why would reverting solve the problem?

**Comment by ukoethe** [comment] 2016-06-10 21:51
Ah, sorry, tested the wrong DLL.

**Comment by ukoethe** [comment] 2016-06-10 22:07
To be fixed by https://github.com/ukoethe/vigra/pull/376

**Comment by stuarteberg** [comment] 2016-06-10 22:12
I can confirm that your new commit eliminates the crash on my machine.

**Comment by ukoethe** [comment] 2016-06-11 09:39
The error is strange, because VIGRA_FINALLY is supposed to do exactly the same thing as HDF5DisableErrorOutput, only in a generic way. Will investigate (input is welcome).

**Comment by ukoethe** [comment] 2016-06-11 10:35
Here is a hypothesis: HDF5 has old-style error handling using `H5Eget_auto1 / H5Eset_auto1` and new-style error handling using `H5Eget_auto2 / H5Eset_auto2`. From the [HDF5 documentation](https://www.hdfgroup.org/HDF5/doc/RM/RM_H5E.html#Error-GetAuto2):

    Mixing the new style and the old style functions will cause a failure.

VIGRA uses new-style, and h5py uses old-style. Thus, my fix isn't actually a fix after all. Even worse, I have no idea what a proper fix would be -- the behavior of h5py is just outside of our control.

**Comment by ukoethe** [comment] 2016-06-11 11:39
Maybe I found a solution, see PR https://github.com/ukoethe/vigra/pull/377.

**Comment by stuarteberg** [comment] 2016-06-13 02:52
Your new solution looks reasonable to me.  I confirmed that the crash no longer occurs when I use your master branch, so I guess you an re-close this issue.

**Closed** 2016-06-13 08:24 UTC
